### ISSUE TITLE
Get SwiftPrometheus up to the Prometheus client library spec

### ISSUE THREAD

**Issue by MrLotU** [swift-server-community/SwiftPrometheus#19]
Spec can be found here: https://prometheus.io/docs/instrumenting/writing_clientlibs

Currently SwiftPrometheus has most of these features, but misses a few. We should implement all of these before a `1.0.0` release to also make SwiftPrometheus listable on the prometheus website.

**Comment by ktoso** [comment]
Great point! Could I suggest we list the missing things as issues so we can solve them one by one? I'm happy to help though would apprichiate a pointer like such finer grained tickets :)

**Comment by MrLotU** [comment]
Thanks for the suggestion! I will go through the entire spec and list everything that's missing (and I'm not already working on 😄)

**Comment by ktoso** [comment]
Awesome, will make it easier to jump in and tackle a few 😄 We can also sollicit it as "help wanted" tickets if we wanted to 👍

**Comment by MrLotU** [comment]
I’ve created some more issues. Please leave a comment or assign yourself if you start working on one so nobody does double work 😃
