### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by ktoso** [swift-server-community/SwiftPrometheus#62]
It would be good to release the 1.0 since the project was promoted to Incubating tho conditionally on the 1.0 release.

https://forums.swift.org/t/sswg-package-maturity-review-2021/51308

SwiftPrometheus
- adopted by various real projects and very responsive maintainer
- @ktoso fills role of secondary maintainer, in addition to the primary author @MrLotU
- Recommendation:
  - conditional on stable release (pending) and 2nd maintainer (done), promote to Incubating

---

Do you need help with making this happen @MrLotU ?
Last time we chatted we just wanted to double check some APIs afair?

We can always cut more releases; it's not like staying in these "alpha" really changes all that much -- we're trying to not break anyone and the project is being used in production right now anyway :-)

**Comment by ktoso** [comment]
AFAICS we're missing those three tickets: https://github.com/MrLotU/SwiftPrometheus/milestone/1

let me know if you'd need/want help on any of those :)

**Comment by MrLotU** [comment]
This was the initial plan, indeed. However more recently I've been thinking about those 3 stories specifically and realised I'm not a huge fan of steering the library the way it'd require.

I'm more and more considering just "wont-fix"-ing them, and releasing a 1.0 in it's current state (Alpha 15).

Open to suggestions & comments though 😄
