### ISSUE TITLE
Add dimension name sanitizer

### ISSUE THREAD

**Issue by vojtarylko** [swift-server-community/SwiftPrometheus#65]
### Feature Request

Add _dimension name_ sanitizer along already existing `LabelSanitizer`.

#### Motivation Behind Feature

Dimension names are limited by Prometheus:

> may contain ASCII letters, numbers, as well as underscores. They must match the regex `[a-zA-Z_][a-zA-Z0-9_]*`
>
> names beginning with `__` are reserved for internal use.

Note: Dimension values may contain any Unicode characters.
Note: The metric name (sanitized by `LabelSanitizer`) follows different rules (`[a-zA-Z_:][a-zA-Z0-9_:]*`).

The reasoning behind this feature is same as in the https://github.com/MrLotU/SwiftPrometheus/issues/29.

**Comment by ktoso** [comment]
Would you send in a PR for this @vojtarylko ? Thanks!

**Comment by vojtarylko** [comment]
@ktoso Will send PR soon.
